version: '3.9'
services:
  postgres:
    image: 'postgres:16.1-alpine3.18'
    restart: always
    environment:
      POSTGRES_PASSWORD: "test123"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  web:
    image: issue-tracker-web
    build: 
      dockerfile: Dockerfile.dev
      context: ../issue-tracker-web
    volumes:
      - ../issue-tracker-web/:/usr/app/
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    depends_on:
      - postgres
  client:
    image: issue-tracker-client
    build:
      dockerfile: Dockerfile.dev
      context: ../issue-tracker-client
    volumes:
      - /usr/app/node_modules
      - ../issue-tracker-client/:/usr/app/
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  postgres-vol:
  issue-tracker-client:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../issue-tracker-client
