version: '3.9'
services:
  postgres:
    image: 'postgres:16.1-alpine3.18'
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "test123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata-release:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  client:
    image: issue-tracker-client
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ../issue-tracker-client
    ports:
      - 2000:80
      - 2001:443
  web:
    image: issue-tracker-web
    build: 
      dockerfile: Dockerfile
      context: ../issue-tracker-web
    volumes:
      - ../issue-tracker-web/:/usr/app/
      - /wildfly-persist/:/bitnami/wildfly
      - /wildfly-conf/standalone.xml:/bitnami/wildfly/configuration/standalone.xml
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres
    environment:
      - WILDFLY_USERNAME=admin
      - WILDFLY_PASSWORD=admin
      - WILDFLY_MANAGEMENT_LISTEN_ADDRESS=localhost
  mail-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: postfixadmin
      MYSQL_USER: postfixadmin
      MYSQL_PASSWORD: example
  mail-server:
    image: 'postfixadmin:3.3.13-fpm-alpine'
    restart: always
    depends_on:
      - mail-db
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: mail-db
      POSTFIXADMIN_DB_USER: postfixadmin
      POSTFIXADMIN_DB_NAME: postfixadmin
      POSTFIXADMIN_DB_PASSWORD: example
