version: '3.9'
services:
  postgres:
    image: 'postgres:16.1-alpine3.18'
    restart: always
    environment:
      POSTGRES_PASSWORD: "test123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  # web:
  #   image: issue-tracker-web
  client:
    image: issue-tracker-client
    build:
      dockerfile: Dockerfile.dev
      context: ../issue-tracker-client
    volumes:
      - /usr/app/node_modules
      - ../issue-tracker-client/:/usr/app/
    ports:
      - "3000:3000"


