version: '3.9'
services:
  postgres:
    image: 'postgres:16.1-alpine3.18'
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "test123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata-release:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  client:
    image: issue-tracker-client
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ../issue-tracker-client
    ports:
      - 2000:80
      - 2001:443